language: node_js
node_js: stable

# assign build branches
branches:
  only:
    - src

# cache this directory
cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - echo '# zanguish.github.io [![Build Status](https://travis-ci.org/zanguish/zanguish.github.io.svg?branch=src)](https://travis-ci.org/zanguish/zanguish.github.io)' > README.md
  - git init
  - git config user.name "zanguish"
  - git config user.email "zw13476587420@163.com"
  - git add .
  - git commit -m "Travis CI Auto Builder"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

env:
 global:
   - GH_REF: github.com/zanguish/zanguish.github.io.git
